# Generated by Django 5.2.8 on 2025-12-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='value1',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='value2',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='alt',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='ls_clear',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='press',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='temp',
            field=models.FloatField(null=True),
        ),
    ]
