# Generated by Django 5.2.8 on 2025-12-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_sensorreading_value1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorreading',
            old_name='ls_clear',
            new_name='EtOH',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='IAQ',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='TVOC',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='alt2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='eCO2',
            field=models.FloatField(null=True),
        ),
    ]
