# Generated by Django 5.2.8 on 2025-12-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_ls_clear_sensorreading_etoh_sensorreading_iaq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='alt2',
        ),
    ]
