# Generated by Django 5.2.8 on 2025-12-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_sensorreading_alt2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='raw_line',
            field=models.TextField(blank=True, null=True),
        ),
    ]
