# Generated by Django 5.2.8 on 2025-12-07 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sensorreading_raw_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='raw_line',
        ),
    ]
