# Generated by Django 5.2.8 on 2025-12-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_sensorreading_raw_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawUART',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raw', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
